github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

image: jsii/superchain

tasks:
  - init: yarn install

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
